name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install exrex
        
    - name: Run create_extended
      run: python create_extended.py
 
      
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Add extended list" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: generated_extended
        github_token: ${{ secrets.access_key }}

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v2 
      with:
        token: ${{ secrets.access_key }}
        commit-message: automated creation of the extended index-list
        title: create extended list
        branch: generated_extended
        base: master
        
  
